FROM golang:1.23.4-alpine AS builder

WORKDIR /app

COPY . .

ENV CGO_ENABLED=0

RUN go build -ldflags="-s -w" -o main main.go

FROM scratch

WORKDIR /app

# Copia apenas o binário da stage de build
COPY --from=builder /app/main .

CMD ["./main"]
