FROM golang:1.23.4-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o main main.go

FROM alpine:3.20

WORKDIR /app

# Copia apenas o binário da stage de build
COPY --from=builder /app/main .

CMD ["./main"]
